### ISSUE TITLE
Symlinked binary on Mac doesn't find story formats in binary location

### ISSUE THREAD

**Issue by Ahmed-M-Tawfik** [tmedwards/tweego#55] opened 2023-06-14 23:13 UTC
**Describe the bug**
When symlinked, tweego cannot find accompanying `storyformats` folder in binary directory.

**To Reproduce**
I symlinked the tweego binary into `/usr/local/bin` from `~/Binaries/tweego-2.1.1-macos-x64` on MacOS 11.7.4 in zsh. When running from a random folder `tweego --help` or `tweego -v` etc, I get the following error: `Story format search directories not found.`

Changing directory into the tweego folder and running those commands produces the expected output (e.g. help docs). Commands don't work when I'm in `~/Binaries`. Commands work after copying `~/Binaries/tweego-2.1.1-macos-x64/storyformats` into `~/Binaries`

**Expected behavior**
Tweego should find the `storyformats` folder in its original directory regardless of working directory.

**Screenshots**
<img width="652" alt="1" src="https://github.com/tmedwards/tweego/assets/46168842/17d8fadf-3753-4f59-9991-a67af0c5a49b">
<img width="420" alt="2" src="https://github.com/tmedwards/tweego/assets/46168842/4ead301b-6547-4f07-a231-c2842538beac">
<img width="196" alt="3" src="https://github.com/tmedwards/tweego/assets/46168842/30e4adbc-3f00-4676-a3b7-6ded7aa024e0">
<img width="870" alt="4" src="https://github.com/tmedwards/tweego/assets/46168842/044f2366-ed1d-44c3-872d-5cf50c20455b">

Testing with `storyformats` copied under `~/Binaries`
<img width="391" alt="5" src="https://github.com/tmedwards/tweego/assets/46168842/d8ee5a61-2fca-4524-a823-e3083f438b94">
<img width="283" alt="6" src="https://github.com/tmedwards/tweego/assets/46168842/7ab75e21-05a3-4a0f-9a6a-c460fe619168">
<img width="185" alt="7" src="https://github.com/tmedwards/tweego/assets/46168842/8b977bed-568b-407b-af86-0c44e38b2d8b">
<img width="195" alt="8" src="https://github.com/tmedwards/tweego/assets/46168842/5f17b123-928d-46e2-96ef-e4eb80c050d0">
<img width="415" alt="9" src="https://github.com/tmedwards/tweego/assets/46168842/7201bdb6-92fd-41bc-8eb8-e688174f09dc">

**Desktop (please complete the following information):**
 - Tweego Version: tweego-2.1.1-macos-x64
 - OS & Version: MacOS 11.7.4 (Big Sur)

**Workaround**
Use TWEEGO_PATH:
<img width="542" alt="Screenshot 2023-06-15 at 00 04 21" src="https://github.com/tmedwards/tweego/assets/46168842/71236130-2f5c-4796-b09c-a7fdce252508">

**Comment by tmedwards** [comment] 2023-06-14 23:56
Duplicate of issue #13

**Closed as completed** 2023-06-14 23:57 UTC
Labels: bug
